### ISSUE TITLE
!add - Not working

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24-Bot/RC24-Bot#48]
When you try to add someone by typing in `!add (Somebody)` it just doesn't work.

**Comment by ArtutoGamer** [comment]
https://media.discordapp.net/attachments/267732619771379713/367280843133026304/Capture_2017-10-10-07-01-13.png

Can you explain what you arguments used?

**Comment by KcrPL** [comment]
\\/

![przechwytywanie](https://user-images.githubusercontent.com/17184296/31385705-825ad93e-adc4-11e7-982b-705bb63dad1e.PNG)

Than nothing happened.

**Comment by spotlightishere** [comment]
This is a known issue -- I'm not exactly sure why. I will revisit this after the transition to Google's Cloud Datastore, mostly because fixing it now would be useless.

**Comment by KcrPL** [comment]
👌

**Comment by spotlightishere** [comment]
this was fixed a while back
