### ISSUE TITLE
!help - Grammar

### ISSUE THREAD

**Issue by sks316** [RiiConnect24-Bot/RC24-Bot#55]
In the `Wii-related` section of the !help command:
```
!code - Manages wii for the user.
!add - Sends your friend wii to another user.

**Comment by sks316** [comment]
It should say something like the following:
`!code - Manages friend codes for the user.
!add - Sends your friend codes to another user.`

**Comment by spotlightishere** [comment]
![Fixed `!help`](https://spotlight-thinks-awoo.should-be.legal/fd40cb.png)
