### ISSUE TITLE
Fix birthday timing

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24-Bot/RC24-Bot#58]
Not sure how easy this would be to fix, but I think the birthday times need to be fixed.

So today was BlueHairedBoi's birthday (the 19th, happy birthday!) but the bot didn't say happy birthday until midnight UTC (that would be the 20th).

**Comment by spotlightishere** [comment]
this is known, i have no immediate interest in fixing it.

**Comment by Artuto** [comment]
This looks to be fixed as d8eb6ea

I'll keep an eye on it anyway

**Comment by Artuto** [comment]
The timer now runs at 8AM CST
